/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.FerramentasLoginDAO;
import java.awt.Color;
import model.User;

/**
 *
 * @author bruno.schneider
 */
public class cadastro extends javax.swing.JFrame {
    FerramentasLoginDAO flog = new FerramentasLoginDAO();
    /**
     * Creates new form NewJFrame
     */
    public cadastro() {
        initComponents();
        campoNome.setBackground(new Color(0,0,0,0));
        campoCpf.setBackground(new Color(0,0,0,0));
        campoCurso.setBackground(new Color(0,0,0,0));
        campoEmail.setBackground(new Color(0,0,0,0));
        campoModulo.setBackground(new Color(0,0,0,0));
        campoNumMatricula.setBackground(new Color(0,0,0,0));
        campoSenha.setBackground(new Color(0,0,0,0));
        campoSenha2.setBackground(new Color(0,0,0,0));
        campoTelefone.setBackground(new Color(0,0,0,0));
        campoTurma.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoNome = new javax.swing.JTextField();
        campoCpf = new javax.swing.JTextField();
        campoNumMatricula = new javax.swing.JTextField();
        campoCurso = new javax.swing.JTextField();
        campoTurma = new javax.swing.JTextField();
        campoSenha = new javax.swing.JTextField();
        campoModulo = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        campoTelefone = new javax.swing.JTextField();
        campoSenha2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btVoltar = new javax.swing.JButton();
        btCadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoNome.setBorder(null);
        getContentPane().add(campoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 146, 240, 20));

        campoCpf.setBorder(null);
        getContentPane().add(campoCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 242, 240, 20));

        campoNumMatricula.setBorder(null);
        getContentPane().add(campoNumMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 336, 240, 20));

        campoCurso.setBorder(null);
        getContentPane().add(campoCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 412, 240, 20));

        campoTurma.setBorder(null);
        getContentPane().add(campoTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 146, 140, 20));

        campoSenha.setBorder(null);
        getContentPane().add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 146, 140, 20));

        campoModulo.setBorder(null);
        getContentPane().add(campoModulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 140, 20));

        campoEmail.setBorder(null);
        getContentPane().add(campoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 336, 190, 20));

        campoTelefone.setBorder(null);
        getContentPane().add(campoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 422, 190, 20));

        campoSenha2.setBorder(null);
        getContentPane().add(campoSenha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 140, 20));

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/faec2-Projetos.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-14, 0, 890, 600));

        btVoltar.setText("jButton1");
        btVoltar.setOpaque(false);
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 80, 60, 60));

        btCadastro.setText("jButton1");
        btCadastro.setOpaque(false);
        btCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 320, 110, 130));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        login lg = new login();
        lg.setVisible(true);
        if(lg.isVisible()){
            this.dispose();
        }
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroActionPerformed
        User u = new User(campoNome.getText(), campoSenha.getText());
        int cpf = Integer.parseInt(campoCpf.getText());
        int numMatricula = Integer.parseInt(campoNumMatricula.getText());
        int turma = Integer.parseInt(campoTurma.getText());
        int modulo = Integer.parseInt(campoModulo.getText());
        int telefone = Integer.parseInt(campoTelefone.getText());
        u = new User(campoNome.getText(), campoSenha.getText() , cpf , numMatricula ,
         campoCurso.getText(), turma, modulo ,campoEmail.getText(), telefone);
        flog.creat(u);
    }//GEN-LAST:event_btCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastro;
    private javax.swing.JButton btVoltar;
    private javax.swing.JTextField campoCpf;
    private javax.swing.JTextField campoCurso;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoModulo;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNumMatricula;
    private javax.swing.JTextField campoSenha;
    private javax.swing.JTextField campoSenha2;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JTextField campoTurma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
