/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.FerramentasLoginDAO;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author bruno.schneider
 */
public class login extends javax.swing.JFrame {
    FerramentasLoginDAO flog = new FerramentasLoginDAO();
    
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
       // campoTxtNome.setOpaque(true);
        campoTxtNome.setBackground(new Color(0,0,0,0));
        campoTxtSenha.setBackground(new Color(0,0,0,0));
        painel.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoTxtNome = new javax.swing.JTextField();
        campoTxtSenha = new javax.swing.JPasswordField();
        painel = new javax.swing.JPanel();
        imagemFundo = new javax.swing.JLabel();
        btCadastro = new javax.swing.JButton();
        btLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoTxtNome.setBorder(null);
        campoTxtNome.setMinimumSize(new java.awt.Dimension(5, 16));
        campoTxtNome.setOpaque(false);
        campoTxtNome.setPreferredSize(new java.awt.Dimension(5, 16));
        getContentPane().add(campoTxtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 256, 180, 20));

        campoTxtSenha.setBorder(null);
        getContentPane().add(campoTxtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 318, 180, -1));

        painel.setPreferredSize(new java.awt.Dimension(905, 601));

        imagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/faec-Projetos.jpg"))); // NOI18N
        imagemFundo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addComponent(imagemFundo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addComponent(imagemFundo)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(painel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        btCadastro.setOpaque(false);
        btCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, 80, 30));

        btLogin.setLabel("");
        btLogin.setOpaque(false);
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 80, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        String x = "";
        for(char c : campoTxtSenha.getPassword()){
            x += c;
        }
        if(flog.getLogin(campoTxtNome.getText(), x) == true){
            JOptionPane.showMessageDialog(this, "Login efetuado com sucesso!!");
        }else{
            JOptionPane.showMessageDialog(this, "Login incorreto!!");
        }
    }//GEN-LAST:event_btLoginActionPerformed

    private void btCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroActionPerformed
        cadastro cd = new cadastro();
        cd.setVisible(true);
        if(cd.isVisible()){
            this.dispose();
        }
    }//GEN-LAST:event_btCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastro;
    private javax.swing.JButton btLogin;
    private javax.swing.JTextField campoTxtNome;
    private javax.swing.JPasswordField campoTxtSenha;
    private javax.swing.JLabel imagemFundo;
    private javax.swing.JPanel painel;
    // End of variables declaration//GEN-END:variables
}
